spring.application.name=loan-api
#change default from 8080 -> 8092
server.port=8092

#connection to postgresSQL db
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/loan
spring.datasource.username=postgres
spring.datasource.password=sodaIT@168

#show sql work
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#swagger
apiTitle=LOAN API
apiDescription=API for managing loans
apiVersion=1.0
apiContactName=Group3
apiContactEmail=sodait25@gmail.com
apiContactUrl=sodait25@gmail.com

#swagger url
# http://localhost:8092/swagger-ui.html



